driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  driver:
    customize:
      memory: 1024
  driver_config:
    box: opscode-ubuntu-14.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

- name: ubuntu-16.04
  driver_config:
    box: opscode-ubuntu-16.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-16.04_chef-provisionerless.box

suites:
  - name: baseserver
    run_list:
      - recipe[baseserver::baseserver]
    attributes:
